//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RezervasyonDBEntities : DbContext
    {
        public RezervasyonDBEntities()
            : base("name=RezervasyonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<iller> illers { get; set; }
        public virtual DbSet<Konaklayan> Konaklayans { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<OdaBilgileri> OdaBilgileris { get; set; }
        public virtual DbSet<RezervasyonBilgileri> RezervasyonBilgileris { get; set; }
        public virtual DbSet<RezervasyonDetay> RezervasyonDetays { get; set; }
        public virtual DbSet<RezervasyonKonaklayanDetay> RezervasyonKonaklayanDetays { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
