//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdaBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OdaBilgileri()
        {
            this.RezervasyonDetays = new HashSet<RezervasyonDetay>();
        }
    
        public int OdaID { get; set; }
        public byte YatakTipiEnum { get; set; }
        public byte OdaTipiEnum { get; set; }
        public decimal Fiyat { get; set; }
        public Nullable<bool> Kullanilabilir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezervasyonDetay> RezervasyonDetays { get; set; }
    }
}
