//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezervasyonBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RezervasyonBilgileri()
        {
            this.RezervasyonDetays = new HashSet<RezervasyonDetay>();
        }
    
        public int RezervasyonID { get; set; }
        public int MusteriID { get; set; }
        public System.DateTime GirisTarihi { get; set; }
        public System.DateTime CikisTarihi { get; set; }
        public int KisiSayisi { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezervasyonDetay> RezervasyonDetays { get; set; }
    }
}
