//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezervasyonDetay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RezervasyonDetay()
        {
            this.RezervasyonKonaklayanDetays = new HashSet<RezervasyonKonaklayanDetay>();
        }
    
        public int RezervasyonDetayID { get; set; }
        public Nullable<int> RezervasyonID { get; set; }
        public Nullable<int> OdaID { get; set; }
    
        public virtual OdaBilgileri OdaBilgileri { get; set; }
        public virtual RezervasyonBilgileri RezervasyonBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezervasyonKonaklayanDetay> RezervasyonKonaklayanDetays { get; set; }
    }
}
